[[api-reference-watcher]]
== Elasticsearch.js Watcher API

[[js-api-method-index-watcher]]
* <<api-watcher-ack_watch,watcher.ackWatch>>
* <<api-watcher-delete_watch,watcher.deleteWatch>>
* <<api-watcher-execute_watch,watcher.executeWatch>>
* <<api-watcher-get_watch,watcher.getWatch>>
* <<api-watcher-info,watcher.info>>
* <<api-watcher-put_watch,watcher.putWatch>>
* <<api-watcher-restart,watcher.restart>>
* <<api-watcher-start,watcher.start>>
* <<api-watcher-stats,watcher.stats>>
* <<api-watcher-stop,watcher.stop>>


[[api-watcher-ack_watch]]
=== `watcher.ackWatch`

[source,js]
--------
client.watcher.ackWatch([params, [callback]])
--------

Throttle the execution of the watch by acknowledging it

The default method is `POST` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-ack-watch.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]
`id`::
`string` -- Watch ID
`masterTimeout`::
`duration` -- Specify timeout for watch write operation



link:#[back to top]


[[api-watcher-delete_watch]]
=== `watcher.deleteWatch`

[source,js]
--------
client.watcher.deleteWatch([params, [callback]])
--------

Delete a specific watch

The default method is `DELETE` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-delete-watch.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]
`force`::
`boolean` -- Specify if this request should be forced and ignore locks
`id`::
`string` -- Watch ID
`masterTimeout`::
`duration` -- Specify timeout for watch write operation



link:#[back to top]


[[api-watcher-execute_watch]]
=== `watcher.executeWatch`

[source,js]
--------
client.watcher.executeWatch([params, [callback]])
--------

Force the execution of the watch actions (eg. for testing)

The default method is `POST` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-execute-watch.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]
`id`::
`string` -- Watch ID



link:#[back to top]


[[api-watcher-get_watch]]
=== `watcher.getWatch`

[source,js]
--------
client.watcher.getWatch([params, [callback]])
--------

Get a specific watch

The default method is `GET` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-get-watch.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]
`id`::
`string` -- Watch ID



link:#[back to top]


[[api-watcher-info]]
=== `watcher.info`

[source,js]
--------
client.watcher.info([params, [callback]])
--------

Return information about the installed Watcher plugin

The default method is `GET` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-info.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]



link:#[back to top]


[[api-watcher-put_watch]]
=== `watcher.putWatch`

[source,js]
--------
client.watcher.putWatch([params, [callback]])
--------

Create a new watch or update an existing one

The default method is `PUT` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-put-watch.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]
`id`::
`string` -- Watch ID
`masterTimeout`::
`duration` -- Specify timeout for watch write operation



link:#[back to top]


[[api-watcher-restart]]
=== `watcher.restart`

[source,js]
--------
client.watcher.restart([params, [callback]])
--------

Restart the watcher service

The default method is `PUT` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-service.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]



link:#[back to top]


[[api-watcher-start]]
=== `watcher.start`

[source,js]
--------
client.watcher.start([params, [callback]])
--------

Start the watcher service

The default method is `PUT` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-service.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]



link:#[back to top]


[[api-watcher-stats]]
=== `watcher.stats`

[source,js]
--------
client.watcher.stats([params, [callback]])
--------

Return statistical information about the watcher service

The default method is `GET` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-stats.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]



link:#[back to top]


[[api-watcher-stop]]
=== `watcher.stop`

[source,js]
--------
client.watcher.stop([params, [callback]])
--------

Stop the watcher service

The default method is `PUT` and the usual <<api-conventions,params and return values>> apply. See http://www.elastic.co/guide/en/watcher/current/appendix-api-service.html[the elasticsearch docs] for more about this method.

// no example

==== Params

[horizontal]



link:#[back to top]


